nginx:
  useCase: "elastic-proxy"
# ============================================================================
# ELASTIC PROXY USE CASE CONFIGURATION (Overrides)
# ============================================================================
elasticProxy:
  enabled: true
  upstreamAuth:
    enabled: true                               
    secretName: "elasticsearch-test-es-elastic-user"
    username: "elastic"                
    passwordKey: "elastic"                      
  
  upstream:
    url: "https://elasticsearch-test-es-http.nginx-demo.svc.cluster.local:9200" # ELASTICSEARCH_URL env var

# ============================================================================
# OPENSHIFT ROUTE CONFIGURATION 
# ============================================================================
routes:
  enabled: true
  items:
    - nameSuffix: "" # Creates a route named: {{ .Release.Name }}-nginx-standard
      host: "test-elastic-proxy.apps.arodevtest.hel.fi"
      path: ""
    - nameSuffix: "-internal" # Creates a route named: {{ .Release.Name }}-nginx-standard-internal
      host: "test-elastic-proxy.api.hel.ninja"
      path: "/internal"