nginx:
  useCase: "file-sharing"
# ==============================================================================
# FILE SHARING - STATIC PROVISIONING MODE
# Mounts an existing Azure File share
# ==============================================================================
fileSharing:
  enabled: true
  storage:
    # STATIC MODE Uses pre-existing Azure File share
    mode: "static"
    pvc:
      enabled: true
      size: "10Gi"
      volumeName: "my-fileshare-pv"
      azureFile:
        enabled: true
        shareName: "test-fileshare"
  locations:
    - path: "/"
      root: "/opt/app-root/src"
      autoindex: true
      additionalConfig: |
        autoindex_exact_size off;
        autoindex_localtime on;
    
    - path: "/downloads"
      alias: "/opt/app-root/src/downloads/"
      autoindex: true
      additionalConfig: |
        add_header Content-Disposition "attachment";
        #autoindex_exact_size off;
        #autoindex_localtime on;
# ============================================================================
# EXTERNAL SECRETS CONFIGURATION (Mandatory Overrides)
# ============================================================================
externalSecrets:
  enabled: true
  azureKeyVault:
    vaultName: "hki-yuygxqll-test-kv"  # REQUIRED
    tenantId: "3feb6bc1-d722-4726-966c-5b58b64df752" # REQUIRED

# ============================================================================
# OPENSHIFT ROUTE CONFIGURATION
# ============================================================================
routes:
  enabled: true
  items:
    - host: "test-fileshare.test.hel.ninja"  # REQUIRED
