nginx:
  useCase: "front-proxy"
  replicaCount: 2
  image:
    full: 'container-registry.platta-net.hel.fi/devops/nginxinc/nginx-unprivileged:alpine-perl'

frontProxy:
  enabled: true
  
  # --- 1a. PLAIN ENV VARIABLES  ---
  env:
    HOST_PROXY: "https://elasticsearch-test-es-http.nginx-demo.svc.cluster.local:9200"
    HOST_EN: "en.example.com"
    HOST_SV: "sv.example.com"
    
    # GEO IP Whitelist List (used to generate proxy_ips.conf)
    PROXY_IP: |
      137.163.145.226/32 1;
      129.0.0.0/8 1;
      10.128.0.0/14 1;
    PROXY_DEFAULT: 0

  # --- 1b. SECRET ENV VARIABLES (secretEnv as separate key) ---
  secretEnv:
    DIGITRANSIT_API_KEY:
      secretName: "elasticsearch-test-es-elastic-user" 
      secretKey: "elastic"  
    CUSTOM_AUTH_TOKEN:
      secretName: "elasticsearch-test-es-elastic-user"
      secretKey: "elastic"
      
  # --- 2. GLOBAL NGINX CONFIGURATION INJECTIONS ---
  globalConfig:
    httpDirectives: |
      # Defines the $allowed variable using the list in proxy_ips.conf
      geo $remote_addr $allowed {
        default $PROXY_DEFAULT; 
        include /opt/app-root/etc/proxy_ips.conf;
      }
      # map $http_user_agent $is_bot { 
      #   default 0;
      #   ~*bot 1;
      # }

    serverDirectives:
      - real_ip_header X-Forwarded-For
      - set_real_ip_from 10.128.0.0/14
      - client_max_body_size 100m
      - proxy_buffers 1024 4k

  # --- 3. PRIMARY SERVER BLOCKS (Simple redirects/proxies) ---
  primaryServers:
    - serverName: "en.example.com"
      redirectPath: "/en"
      
  # --- 4. CUSTOM SERVER BLOCKS (Complex logic/API proxies) ---
  customServers:
    # - serverName: digitransit-proxy.api.hel.fi
    #   locations:
    #     - path: "/"
    #       proxyPass: https://api.digitransit.fi/
    #       additionalConfig: |
    #         proxy_set_header digitransit-subscription-key $digitransit_api_key;
            
    - serverName: localhost
      locations:
        - path: "= /"
          additionalConfig: |
            if ($allowed = 0) {
              return 403 "blocked $remote_addr";
            }
          proxyPass: https://elasticsearch-test-es-http.nginx-demo.svc.cluster.local:9200
          
    # - serverName: xn--ptkset-buaa7n.hel.fi
    #   locations:
    #     - path: "/"
    #       additionalConfig: |
    #         return 301 https://paatokset.hel.fi/$uri;

observability:
  metrics:
    enabled: true
    type: "stub_status"
    stubStatus:
      path: "/nginx_status"

routes:
  enabled: false  # Disable routes for front-proxy, use ingress instead