{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "mailpit-openshift.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mailpit-openshift.labels" . | nindent 4 }}
  {{- if .Values.route.annotations }}
  annotations:
    {{- range $key, $val := .Values.route.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host | quote }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "mailpit-openshift.fullname" . }}-http
    weight: 100
  port:
    targetPort: http
  tls:
    termination: {{ .Values.route.tls.termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy | default "Redirect" }}
  wildcardPolicy: None
{{- end }}