{{- include "nginx-standard.validateCache" . -}}
{{- include "nginx-standard.validateElasticProxy" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx-standard.configmapName" . }}
  namespace: {{ include "nginx-standard.namespace" . }}
  labels:
    {{- include "nginx-standard.labels" . | nindent 4 }}
data:
  nginx.conf: |-
{{ include "nginx-standard.nginxMainConf" . | nindent 4 }}
  
  server.conf: |-
{{ include "nginx-standard.nginxServerConf" . | nindent 4 }}

{{- if and (eq .Values.nginx.useCase "front-proxy") .Values.frontProxy.enabled (.Values.frontProxy.env.PROXY_IP) }}
  proxy_ips.conf: |-
{{ .Values.frontProxy.env.PROXY_IP | trim | nindent 4 }}
{{- end }}