{{- if eq (include "nginx-standard.externalSecretsEnabled" .) "true" }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nginx-standard.externalSecretName" . }}
  namespace: {{ include "nginx-standard.namespace" . }}
  labels:
    {{- include "nginx-standard.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    kind: SecretStore
    name: {{ include "nginx-standard.secretStoreName" . }}
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: {{ include "nginx-standard.secretName" . }}
  data:
    - secretKey: azurestorageaccountname
      remoteRef:
        key: {{ .Values.externalSecrets.azureKeyVault.storageAccountNameKey | default "AZURE-STORAGE-ACCOUNT-NAME" }}
    - secretKey: azurestorageaccountkey
      remoteRef:
        key: {{ .Values.externalSecrets.azureKeyVault.storageAccountKeyKey | default "AZURE-STORAGE-ACCOUNT-KEY" }}
{{- end }}