{{- if .Values.routes.enabled }}
{{- $fullName := include "nginx-standard.fullname" . }}
{{- range $i, $route := .Values.routes.items }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ $fullName }}{{ $route.nameSuffix }}
  namespace: {{ include "nginx-standard.namespace" $ }}
  labels:
    {{- include "nginx-standard.labels" $ | nindent 4 }}
  annotations:
    {{- $globalAnnotations := default dict $.Values.routes.annotations }}
    {{- $itemAnnotations := default dict $route.annotations }}
    {{- $annotations := mergeOverwrite $globalAnnotations $itemAnnotations }}
    {{- toYaml $annotations | nindent 4 }}
spec:
  host: {{ $route.host | required "Host is required" }}
  path: {{ $route.path | default "" }}
  to:
    kind: Service
    name: {{ $fullName }}-svc
    weight: 100
  port:
    targetPort: {{ $.Values.nginx.service.name | default "http" }}
  tls:
    {{- with $route.tls }}
    # If 'tls' is defined for the specific route item, use its values
    termination: {{ .termination | default "edge" }}
    insecureEdgeTerminationPolicy: {{ .insecureEdgeTerminationPolicy | default "Redirect" }}
    {{- else }}
    # If 'tls' is NOT defined, use the chart's defaults (Edge/Redirect)
    termination: "edge"
    insecureEdgeTerminationPolicy: "Redirect"
    {{- end }}
{{- end }}
{{- end }}