{{- if eq (include "nginx-standard.externalSecretsEnabled" .) "true" }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "nginx-standard.secretStoreName" . }}
  namespace: {{ include "nginx-standard.namespace" . }}
  labels:
    {{- include "nginx-standard.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authSecretRef:
        clientId:
          key: clientId
          name: {{ .Values.externalSecrets.servicePrincipal.secretName | default "azure-service-principal" }}
        clientSecret:
          key: clientSecret
          name: {{ .Values.externalSecrets.servicePrincipal.secretName | default "azure-service-principal" }}
      authType: ServicePrincipal
      environmentType: PublicCloud
      tenantId: {{ .Values.externalSecrets.azureKeyVault.tenantId | required "externalSecrets.azureKeyVault.tenantId is required when externalSecrets.enabled is true" }}
      vaultUrl: {{ include "nginx-standard.vaultUrl" . }}
{{- end }}