{{- if .Values.route.enabled }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "helfi-proxy-nginx.fullname" . }}
  labels:
    {{- include "helfi-proxy-nginx.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.route.annotations | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "helfi-proxy-nginx.fullname" . }}
    weight: 100
  port:
    targetPort: 8080-tcp
  {{- if .Values.route.tls.enabled }}
  tls:
    termination: {{ .Values.route.tls.termination }}
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}

{{- if .Values.additionalRoutes }}
{{- range .Values.additionalRoutes }}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "helfi-proxy-nginx.fullname" $ }}-{{ .host | replace "." "-" }}
  labels:
    {{- include "helfi-proxy-nginx.labels" $ | nindent 4 }}
  annotations:
    {{- toYaml .annotations | nindent 4 }}
spec:
  host: {{ .host }}
  to:
    kind: Service
    name: {{ include "helfi-proxy-nginx.fullname" $ }}
    weight: 100
  port:
    targetPort: 8080-tcp
  {{- if .tls.enabled }}
  tls:
    termination: {{ .tls.termination }}
    insecureEdgeTerminationPolicy: {{ .tls.insecureEdgeTerminationPolicy }}
  {{- end }}
  wildcardPolicy: None
{{- end }}
{{- end }}