---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "varnish-drupal.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "varnish-drupal.labels" . | nindent 4 }}